name: Build and Test

env:
  PKGDIR: "packages/basemap"
  CIBW_BUILD_VERBOSITY: 1
  PYTHONUNBUFFERED: "1"
  PYTHONWARNINGS: "ignore:DEPRECATION"
  GEO_VERSION: "3.6.5"

on:
  push:
    paths:
      - ".github/workflows/**"
      - "packages/basemap/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "packages/basemap/**"
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: "3.16.x"

      - name: Setup C++ toolchain (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Setup Visual Studio Developer Command Prompt
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup C++ toolchain (macOS)
        if: runner.os == 'macOS'
        run: |
          xcode-select --install || true

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.2

      - name: Set GEO_DIR (Unix)
        if: runner.os != 'Windows'
        run: |
          echo "GEOS_DIR=$HOME/geo" >> $GITHUB_ENV
          echo "Runner OS: ${RUNNER_OS}"
          echo "Set GEO_DIR to: ${GEOS_DIR}"
          ls -la ${{ env.GEO_DIR }}

      - name: Set GEO_DIR (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          echo "GEOS_DIR=./geo" >> $GITHUB_ENV
          echo "Runner OS: ${RUNNER_OS}"
          echo "Set GEO_DIR to: ${GEO_DIR}"
          ls -la ${{ env.GEO_DIR }}

      - name: Build wheels
        env:
          CIBW_BUILD: cp{39,310,311,312}-{manylinux_x86_64,win_amd64,macosx_x86_64}
          CIBW_ARCHS_MACOS: x86_64
          CIBW_SKIP: "*-manylinux_i686 *-musllinux* pp*"

          CIBW_BEFORE_BUILD: >
            python -c "import utils; utils.GeosLibrary('${{ env.GEO_VERSION }}').build('${{ env.GEOS_DIR}}', njobs=16)"

          CIBW_TEST_COMMAND: >-
            python -c "import mpl_toolkits.basemap" &&
            cd {project} &&
            pip install pytest pytest-cov &&
            python -m pytest --cov="mpl_toolkits.basemap" --cov-report=term --ignore=dist --ignore=build

        run: |
          cd ${{ env.PKGDIR }}
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ${{ env.PKGDIR }}/wheelhouse/*.whl
